### ISSUE TITLE
How does the view-counter get the client IP?

### ISSUE THREAD

**Issue by airinghost** [hi019/better-view-counter#4]
Hi, this tool is really simple and useful, thank you!

But I just have a trouble: 

The application is running at default port 3000 on my VPS; the `?unique=true` is applied, and I make a use of nginx to proxy it. Then I finds that the view-counter doesn't add 1 after I changed my client IP address. And it works again when the nginx is stopped (using http://ip.address directly ).  

So how does the view-counter getting the client IP? Through HTTP Request Headers or something else? I have tried the CDN and added the `X-Forwarded-For` header but it seems not working.

Looking forward to your help. Thank you!

**Comment by hi019** [comment]
It just uses the request's ip. But I assume the request is now proxied through Github's servers, which is why unique mode is no longer working when embedded on Github.

**Comment by airinghost** [comment]
> It just uses the request's ip. But I assume the request is now proxied through Github's servers, which is why unique mode is no longer working when embedded on Github.

Thank you for your attention! Well.. in fact I use the view-counter just for my blog, and for GitHub views counts, I chose the project "hits". 

And this is the solution I applied: using the Fiber's `ListenTLS` then let view-counter as a files server instead of nginx.

Thanks for your project again!

**Comment by hi019** [comment]
Ok, so is the problem fixed? Looking at this again, I think I understand your problem better now. better-view-counter doesn't support using X-Forwarded-For or similar headers to get the IP. I see you have made a fork -- if you want to add this functionality, take a look at the [ProxyHeader](https://docs.gofiber.io/api/fiber#config) config value.

Note, even if you are able to get the user's ip from behind nginx, Github might still proxy the request through its own servers, as I mentioned in my previous reply.

**Comment by airinghost** [comment]
> so is the problem fixed? 

Yes. I don't need nginx any more so there're no problems now.

> take a look at the ProxyHeader config value.

Thank you! This helps a lot.

> Github might still proxy the request through its own servers

Yes, I get it.

You're really a good man, my friend. Thank you!

**Comment by hi019** [comment]
No problem!
